### ISSUE TITLE
newdoc validation?

### ISSUE THREAD

**Issue by yzimmerm** [redhat-documentation/newdoc#29]
Hi, 
The _newdoc_ script has been extremely helpful, but extending it to validating files?! Maybe you can create a copy or alias for validation. It is confusing when a script called _newdoc_ makes nothing new and requires an existing filename as a parameter.

**Comment by msuchane** [comment]
That's a valid point. I weighed my options when implementing the validation feature. I picked the approach of integrating validation into newdoc because it requires the least amount of effort on the writer's part to install the tool. But if the scope of validation significantly grows, and newdoc is used in environments like CI, it will make more sense to distribute the validation separately.

So in short, I'm taking your suggestion into consideration and I'll keep an eye on the other factors.

**Comment by VladimirSlavik** [comment]
It could work like (g)zip does - check the invocation, and if it's called as `newdoc`, default to create, if as `valdoc`, default to validate...

**Comment by msuchane** [comment]
So, having an alias or link like `valdoc` or `validatedoc` would be easy to do in `newdoc`. But I confess I don't know how to _package_ that link in RPM. The packaging process between Rust and RPM is pretty opaque to me, which is the reason why `newdoc` has no man page, for instance. If somebody helps me with the packaging aspect, I'll be happy to add the alias.

**Comment by jhradilek** [comment]
With validation being deprecated in version 2.12.0, I believe this issue and several others discussing various aspects of validation can be closed now.

**Comment by msuchane** [comment]
Good point. I'm closing this issue.
